spring.application.name=busapp

# 1. Cấu hình kết nối SQL Server (Sử dụng cổng 1433)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bus_management_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 2. Cấu hình JPA cho SQL Server
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
